## Practice Data Wrangling

![](https://iili.io/3S2kRyu.png)

## Pandas


Pandas is a Python library extensively used for data analysis and manipulation. It provides data structures like DataFrames, which are similar to tables, and Series, which are like lists or columns in a table. These structures allow for efficient handling and processing of structured data. Pandas is built on top of NumPy and integrates well with other scientific computing libraries. It simplifies tasks such as data cleaning, transformation, and analysis, making it a fundamental tool for data scientists and analysts.

### Installing and Importing Pandas

Installing Pandas
```
pip install pandas
```

In [1]:
%pip install pandas

Collecting pandas
  Using cached pandas-2.2.3-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.6-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.2.3-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
Downloading numpy-2.2.6-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 7.8 MB/s eta 0:00:00a 0:00:01
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [pandas]2m3/4 [pandas]
Successfully installed numpy-2.2.6 pandas-2.2.3 pytz-2025.2 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

importing pandas

In [2]:
## pd is widely used alias for pandas
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 50)

### Creating Series and Pandas Data Frame

#### 1. Creating Series
 A Pandas Series is a one-dimensional labeled array capable of holding data of any type. It is similar to a column in a spreadsheet or a SQL table. The labels for the Series are collectively known as the index. A Series can be created from a variety of data types, including lists, dictionaries, and NumPy arrays.

In [36]:
### Ex-1-Task-1

s = None 
a = [1, 2, 3, 4, 5, 6]
# Task: create a series using list 
### BEGIN SOLUTION 
# YOUR CODE HERE
s = pd.Series(a)
s
# raise NotImplementedError() 
### END SOLUTION

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [37]:
### Ex-1-Task-2
a = {
    'a': 80,
    'b': 90,
    'c': 100
}
s = None 
## Task: Create a series using dictionary

### BEGIN SOLUTION 
# YOUR CODE HERE
s = pd.Series(a)
s
# raise NotImplementedError() 
### END SOLUTION

a     80
b     90
c    100
dtype: int64

In [38]:
### Ex-1-Task-3
a = [1, 2, 3, 4, 5, 6]
a = np.array(a)
s = None
## Creating a series using numpy array
### BEGIN SOLUTION 
# YOUR CODE HERE
s = pd.Series(a)
s
# raise NotImplementedError() 
### END SOLUTION

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [39]:
### Ex-1-Task-4
population = {
    'Nepal': 30000000,
    'India': 1463865525,
    'Pakistan':255219554,
    'China': 1416096094
}
s = None
## Create a series with name 'population' and dtype='int64' 
### BEGIN SOLUTION 
# YOUR CODE HERE
s = pd.Series(population, dtype='int64', name='population')
s
# raise NotImplementedError() 
### END SOLUTION

Nepal         30000000
India       1463865525
Pakistan     255219554
China       1416096094
Name: population, dtype: int64

#### 2. Creating DataFrame

In [43]:
### Ex-2-Task-1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
df = None 
# Creating Data Frame from Python List
### BEGIN SOLUTION 
# YOUR CODE HERE
df = pd.DataFrame(a, columns=['numbers'])
df
# raise NotImplementedError() 
### END SOLUTION

   numbers
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10

In [44]:
### Ex-2-Task-2
my_list = [['A', 1], ['B', 2], ['C', 3], ['D', 4]]
# Creating Data Frame from List of List
### BEGIN SOLUTION 
# YOUR CODE HERE
df = pd.DataFrame(my_list, columns=['letter', 'number'])
df
# raise NotImplementedError() 
### END SOLUTION

  letter  number
0      A       1
1      B       2
2      C       3
3      D       4

In [45]:
### Ex-2-Task-3
my_data = {
    'country': ['Nepal', 'India', 'China'],
    'Population': [30000000, 1463865525, 1416096094]
}
df = None
# Creating Data Frame using Python Dictionary
### BEGIN SOLUTION 
# YOUR CODE HERE
df = pd.DataFrame(my_data)
df
# raise NotImplementedError() 
### END SOLUTION

  country  Population
0   Nepal    30000000
1   India  1463865525
2   China  1416096094

## Data Loading and Inspection

### Reading Data
A simple way to store big data is to use CSV files (comma Seperated files) or Parquet Files. 
- df_sales --> computed_insight_success_of_active_sellers.csv'
- df_product --> summer-products-with-rating-and-performance_2020-08.csv

In [48]:
### Ex-3-Task-1
df_sales = None
df_product = None

# reading CSV file
### BEGIN SOLUTION 
# YOUR CODE HERE
df_sales = pd.read_csv('computed_insight_success_of_active_sellers.csv')
df_product = pd.read_csv('summer-products-with-rating-and-performance_2020-08.csv')
# raise NotImplementedError() 
### END SOLUTION

### Basic Inspection

In [49]:
### Ex-3-Task-2
head_df = None 
tail_df = None 
desribe_num_df = None
desribe_cate_df = None
# check the first 10 records of the sales dataframe 
# check the last 10 records of the product dataframe
## Check the description of the numerical and categorical columns of prodcut dataframe
### BEGIN SOLUTION 
# YOUR CODE HERE
head_df = df_sales.head(10)
tail_df = df_product.tail(10)
desribe_num_df = df_product.describe()
desribe_cate_df = df_product.describe(include=[object])
print(head_df, tail_df, desribe_num_df, desribe_cate_df, sep='\n\n')
# raise NotImplementedError() 
### END SOLUTION

                 merchantid  listedproducts  totalunitssold  \
0  5357bcf2bb72c5504882e889               2          120000
1  5708773c3c02161b3f8c7900               5          107100
2  5417aada4ad3ab27e954b76c               2          100007
3  570f3a713a698c14278bb51e               1          100000
4  53082ea15aefb07dfe1f2a4f               1          100000
5  53f2beb39020ee03566d6e18               1          100000
6  5926c5ace8ff5525241b368d               7           96000
7  5860c757b1e41d4d67d183e8               4           90100
8  52bd3ddb34067e4620a4c62d               3           80000
9  5a7b23a69bda4e3d375e7b3f               5           80000

   meanunitssoldperproduct  rating  merchantratingscount  meanproductprices  \
0                  60000.0   4.219              320031.0               9.00
1                  21420.0   3.934              139223.0               7.76
2                  50004.0   4.053              108048.0               8.00
3                 100000.0   3.889               19248.0               5.67
4                 100000.0   4.036              366898.0               5.00
5                 100000.0   4.067              330405.0               5.77
6                  13714.0   4.139               55499.0               6.69
7                  22525.0   4.049              151249.0               3.43
8                  26667.0   4.104              839882.0               7.22
9                  16000.0   3.966               12974.0               8.40

   meanretailprices  averagediscount  meandiscount  meanproductratingscount  \
0             20.00             54.0         54.00                   8836.0
1             34.20             61.0         61.00                   4010.0
2              8.00             -1.0         -1.00                   5531.0
3             19.00             71.0         71.00                  18393.0
4             33.00             85.0         85.00                  13789.0
5             48.00             88.0         88.00                  20744.0
6              6.29             -4.0         -3.86                   2250.0
7              3.75             11.0         11.00                   6290.0
8             14.67             33.0         33.33                   6136.0
9              7.80             -7.0         -6.80                   2093.0

   totalurgencycount  urgencytextrate
0                1.0             50.0
1                3.0             60.0
2                NaN              NaN
3                1.0            100.0
4                NaN              NaN
5                NaN              NaN
6                1.0             14.0
7                2.0             50.0
8                1.0             33.0
9                1.0             20.0

                                                  title  \
1563  ZANZEA Femmes Été Polka Dot Kaftan Beach Club ...
1564  2018 Femme mode d'été en dentelle Patchwork Pa...
1565  Nouveau Pantalon De Mode D'été Femmes Leggings...
1566  Robe mi-longue d'été à manches courtes pour fe...
1567  Combinaison sans manches pour femmes couleur u...
1568  Nouvelle Mode Femmes Bohême Pissenlit Imprimer...
1569  10 couleurs femmes shorts d'été lacent ceintur...
1570  Nouveautés Hommes Siwmwear Beach-Shorts Hommes...
1571  Mode femmes d'été sans manches robes col en V ...
1572  Pantalon de yoga pour femmes à la mode Slim Fi...

                                             title_orig  price  retail_price  \
1563  ZANZEA Women Summer Polka Dot Kaftan Beach Clu...  15.00            92
1564  2018 Women fashion Summer Lace Patchwork Tank ...   5.91             5
1565  New Summer Fashion Trousers Women Leggings Rip...   3.00             8
1566  Womens Short Sleeve Baggy Summer Beach Midi Dr...  11.00           134
1567  Sleeveless Solid Color Women Jumpsuit Ladies S...   8.00             7
1568  New Fashion Women Bohemia Dandelion Print Tee ...   6.00             9
1569  10 Color Women Summer Shorts Lace Up Elastic W...   2.00            56
1570  New Men Siwmwear Beach-Shorts Men Summer Quick...   5.00            19
1571  Fashion Women Summer Sleeveless Dresses V Neck...  13.00            11
1572  Fashion Women Yoga Pants Slim Fit Fitness Runn...   7.00             6

     currency_buyer  units_sold  uses_ad_boosts  rating  rating_count  \
1563            EUR         100               0    3.51            74
1564            EUR        1000               0    3.38           414
1565            EUR         100               1    3.79            57
1566            EUR         100               1    3.54            28
1567            EUR       20000               1    4.25          3127
1568            EUR       10000               1    4.08          1367
1569            EUR         100               1    3.07            28
1570            EUR         100               0    3.71            59
1571            EUR         100               0    2.50             2
1572            EUR         100               1    4.07            14

      rating_five_count  rating_four_count  rating_three_count  \
1563               26.0               15.0                15.0
1564              156.0               58.0                72.0
1565               25.0               10.0                13.0
1566                7.0               11.0                 4.0
1567             1919.0              580.0               304.0
1568              722.0              293.0               185.0
1569               11.0                3.0                 1.0
1570               24.0               15.0                 8.0
1571                0.0                1.0                 0.0
1572                8.0                3.0                 1.0

      rating_two_count  rating_one_count  badges_count  badge_local_product  \
1563               7.0              11.0             0                    0
1564              45.0              83.0             0                    0
1565               3.0               6.0             0                    0
1566               2.0               4.0             0                    0
1567             128.0             196.0             1                    0
1568              77.0              90.0             0                    0
1569               3.0              10.0             0                    0
1570               3.0               9.0             0                    0
1571               0.0               1.0             0                    0
1572               0.0               2.0             0                    0

      badge_product_quality  badge_fast_shipping  \
1563                      0                    0
1564                      0                    0
1565                      0                    0
1566                      0                    0
1567                      1                    0
1568                      0                    0
1569                      0                    0
1570                      0                    0
1571                      0                    0
1572                      0                    0

                                                   tags product_color  \
1563  Summer,loosedresse,kaftan,long dress,baggydres...           red
1564  blouse,Summer,Vest,Fashion,Women Blouse,sleeve...         White
1565  Summer,Leggings,Fashion,high waist,pants,slim,...       skyblue
1566  Summer,Shift Dress,Sleeve,shirt dress,long dre...         black
1567  bodycon jumpsuits,nightwear,Shorts,slim,Body S...         black
1568  bohemia,Plus Size,dandelionfloralprinted,short...      navyblue
1569  Summer,Panties,Elastic,Lace,Casual pants,casua...     lightblue
1570  runningshort,Beach Shorts,beachpant,menbeachsh...         white
1571  Summer,fashion women,Fashion,Lace,Dresses,Dres...         white
1572  Summer,Leggings,slim,Yoga,pants,Slim Fit,Women...           red

     product_variation_size_id  product_variation_inventory  \
1563                         L                           50
1564                         S                           50
1565                        XS                            1
1566                         S                           50
1567                         M                           50
1568                         S                           50
1569                         S                            2
1570                    SIZE S                           15
1571                   Size S.                           36
1572                         S                           50

     shipping_option_name  shipping_option_price  shipping_is_express  \
1563         Envio Padrão                      4                    0
1564   Livraison standard                      2                    0
1565   Livraison standard                      1                    0
1566   Livraison standard                      3                    0
1567   Livraison standard                      2                    0
1568   Livraison standard                      2                    0
1569   Livraison standard                      1                    0
1570   Livraison standard                      2                    0
1571   Livraison standard                      3                    0
1572   Livraison standard                      2                    0

      countries_shipped_to  inventory_total  has_urgency_banner  \
1563                    38               50                 NaN
1564                    36               50                 1.0
1565                    41               50                 1.0
1566                    46               50                 NaN
1567                    44               50                 NaN
1568                    41               50                 NaN
1569                    26               50                 1.0
1570                    11               50                 NaN
1571                    29               50                 NaN
1572                    41               50                 NaN

            urgency_text origin_country           merchant_title  \
1563                 NaN             CN          fashionforgirls
1564  Quantité limitée !             CN                  liminny
1565  Quantité limitée !             CN                 bujizhan
1566                 NaN             CN                  SCOMELY
1567                 NaN             CN                Rell Mail
1568                 NaN             CN             cxuelin99126
1569  Quantité limitée !             CN  sell best quality goods
1570                 NaN             CN               shixueying
1571                 NaN             CN                    modai
1572                 NaN             CN           AISHOPPINGMALL

             merchant_name                          merchant_info_subtitle  \
1563       guangzhouchanny  88% Feedback positivo (151,914 classificações)
1564               liminny               81 % avis positifs (12,134 notes)
1565              bujizhan                                   (4,080 notes)
1566               scomely                86 % avis positifs (1,926 notes)
1567              rellmail               88 % avis positifs (16,803 notes)
1568          cxuelin99126                90 % avis positifs (5,316 notes)
1569  sellbestqualitygoods                                   (4,435 notes)
1570            shixueying                  86 % avis positifs (210 notes)
1571                 modai                   77 % avis positifs (31 notes)
1572        aishoppingmall                90 % avis positifs (7,023 notes)

      merchant_rating_count  merchant_rating               merchant_id  \
1563                 151914         4.127921  53aa664438d3046ee44a5024
1564                  12134         3.866903  58aec90823ef726994a323fe
1565                   4080         3.987990  584a7a381591451e4e3af3df
1566                   1926         4.071651  593402ae25c4f54ed4e0abdf
1567                  16803         4.155032  56455b13b15aab129db58cb7
1568                   5316         4.224605  5b507899ab577736508a0782
1569                   4435         3.696054  54d83b6b6b8a771e478558de
1570                    210         3.961905  5b42da1bf64320209fc8da69
1571                     31         3.774194  5d56b32c40defd78043d5af9
1572                   7023         4.235939  5a409cf87b584e7951b2e25f

      merchant_has_profile_picture merchant_profile_picture  \
1563                             0                      NaN
1564                             0                      NaN
1565                             0                      NaN
1566                             0                      NaN
1567                             0                      NaN
1568                             0                      NaN
1569                             0                      NaN
1570                             0                      NaN
1571                             0                      NaN
1572                             0                      NaN

                                          product_url  \
1563  https://www.wish.com/c/5da04c1f5949a226113006f1
1564  https://www.wish.com/c/5b4ed29514f0765a8a844592
1565  https://www.wish.com/c/5e8f0165e815903d022a3c7c
1566  https://www.wish.com/c/5d1060d39ed281190dfcec91
1567  https://www.wish.com/c/5c91a7ae7cfe8e4e64c36d97
1568  https://www.wish.com/c/5d5fadc99febd9356cbc52ee
1569  https://www.wish.com/c/5eccd22b4497b86fd48f16b4
1570  https://www.wish.com/c/5e74be96034d613d42b52dfe
1571  https://www.wish.com/c/5eda07ab0e295c2097c36590
1572  https://www.wish.com/c/5e857321f53c3d2d8f25e7ed

                                        product_picture  \
1563  https://contestimg.wish.com/api/webimage/5da04...
1564  https://contestimg.wish.com/api/webimage/5b4ed...
1565  https://contestimg.wish.com/api/webimage/5e8f0...
1566  https://contestimg.wish.com/api/webimage/5d106...
1567  https://contestimg.wish.com/api/webimage/5c91a...
1568  https://contestimg.wish.com/api/webimage/5d5fa...
1569  https://contestimg.wish.com/api/webimage/5eccd...
1570  https://contestimg.wish.com/api/webimage/5e74b...
1571  https://contestimg.wish.com/api/webimage/5eda0...
1572  https://contestimg.wish.com/api/webimage/5e857...

                    product_id   theme crawl_month
1563  5da04c1f5949a226113006f1  summer     2020-08
1564  5b4ed29514f0765a8a844592  summer     2020-08
1565  5e8f0165e815903d022a3c7c  summer     2020-08
1566  5d1060d39ed281190dfcec91  summer     2020-08
1567  5c91a7ae7cfe8e4e64c36d97  summer     2020-08
1568  5d5fadc99febd9356cbc52ee  summer     2020-08
1569  5eccd22b4497b86fd48f16b4  summer     2020-08
1570  5e74be96034d613d42b52dfe  summer     2020-08
1571  5eda07ab0e295c2097c36590  summer     2020-08
1572  5e857321f53c3d2d8f25e7ed  summer     2020-08

             price  retail_price     units_sold  uses_ad_boosts       rating  \
count  1573.000000   1573.000000    1573.000000     1573.000000  1573.000000
mean      8.325372     23.288620    4339.005086        0.432931     3.820896
std       3.932030     30.357863    9356.539302        0.495639     0.515374
min       1.000000      1.000000       1.000000        0.000000     1.000000
25%       5.810000      7.000000     100.000000        0.000000     3.550000
50%       8.000000     10.000000    1000.000000        0.000000     3.850000
75%      11.000000     26.000000    5000.000000        1.000000     4.110000
max      49.000000    252.000000  100000.000000        1.000000     5.000000

       rating_count  rating_five_count  rating_four_count  rating_three_count  \
count   1573.000000        1528.000000        1528.000000         1528.000000
mean     889.659250         442.263743         179.599476          134.549738
std     1983.928834         980.203270         400.516231          311.690656
min        0.000000           0.000000           0.000000            0.000000
25%       24.000000          12.000000           5.000000            4.000000
50%      150.000000          79.000000          31.500000           24.000000
75%      855.000000         413.500000         168.250000          129.250000
max    20744.000000       11548.000000        4152.000000         3658.000000

       rating_two_count  rating_one_count  badges_count  badge_local_product  \
count       1528.000000       1528.000000   1573.000000          1573.000000
mean          63.711387         95.735602      0.105531             0.018436
std          151.343933        214.075544      0.340709             0.134565
min            0.000000          0.000000      0.000000             0.000000
25%            2.000000          4.000000      0.000000             0.000000
50%           11.000000         20.000000      0.000000             0.000000
75%           62.000000         94.000000      0.000000             0.000000
max         2003.000000       2789.000000      3.000000             1.000000

       badge_product_quality  badge_fast_shipping  \
count            1573.000000          1573.000000
mean                0.074380             0.012715
std                 0.262472             0.112075
min                 0.000000             0.000000
25%                 0.000000             0.000000
50%                 0.000000             0.000000
75%                 0.000000             0.000000
max                 1.000000             1.000000

       product_variation_inventory  shipping_option_price  \
count                  1573.000000            1573.000000
mean                     33.081373               2.345200
std                      21.353137               1.024371
min                       1.000000               1.000000
25%                       6.000000               2.000000
50%                      50.000000               2.000000
75%                      50.000000               3.000000
max                      50.000000              12.000000

       shipping_is_express  countries_shipped_to  inventory_total  \
count          1573.000000           1573.000000      1573.000000
mean              0.002543             40.456453        49.821360
std               0.050379             20.301203         2.562799
min               0.000000              6.000000         1.000000
25%               0.000000             31.000000        50.000000
50%               0.000000             40.000000        50.000000
75%               0.000000             43.000000        50.000000
max               1.000000            140.000000        50.000000

       has_urgency_banner  merchant_rating_count  merchant_rating  \
count               473.0           1.573000e+03      1573.000000
mean                  1.0           2.649583e+04         4.032345
std                   0.0           7.847446e+04         0.204768
min                   1.0           0.000000e+00         2.333333
25%                   1.0           1.987000e+03         3.917353
50%                   1.0           7.936000e+03         4.040650
75%                   1.0           2.456400e+04         4.161797
max                   1.0           2.174765e+06         5.000000

       merchant_has_profile_picture
count                   1573.000000
mean                       0.143675
std                        0.350871
min                        0.000000
25%                        0.000000
50%                        0.000000
75%                        0.000000
max                        1.000000

                                                    title  \
count                                                1573
unique                                               1201
top     Nouvelle mode d'été femmes robe décontractée c...
freq                                                   24

                                               title_orig currency_buyer  \
count                                                1573           1573
unique                                               1203              1
top     New Fashion Summer Women Casual Dress Round Ne...            EUR

In [50]:
### Ex-3-Task-3

# set merchant id as the index of the sales dataframe and check index
### BEGIN SOLUTION 
# YOUR CODE HERE
df_sales.set_index('merchantid', inplace=True)
print(df_sales.index)
# raise NotImplementedError() 
### END SOLUTION

Index(['5357bcf2bb72c5504882e889', '5708773c3c02161b3f8c7900',
       '5417aada4ad3ab27e954b76c', '570f3a713a698c14278bb51e',
       '53082ea15aefb07dfe1f2a4f', '53f2beb39020ee03566d6e18',
       '5926c5ace8ff5525241b368d', '5860c757b1e41d4d67d183e8',
       '52bd3ddb34067e4620a4c62d', '5a7b23a69bda4e3d375e7b3f',
       ...
       '574d559cb06e205d099d9107', '5db248327c0d0800c24fc084',
       '54365c349719cd57af2b449b', '581c54c4dd99164b808ca531',
       '564d8f2f3a698c01d97fbb81', '567bad8582c35f28103e5813',
       '5b24edf0d1c360301099e9c6', '5d417e7070327a2743021677',
       '5add589edb5f1f32114d07df', '5d4b8931933fb13f8a1fe232'],
      dtype='object', name='merchantid', length=958)

In [51]:
### Ex-3-Task-4
sorted_df = None
## Sort the sales dataframe by rating in Ascending Order, if two records have same rating then sort in descending order by total unit sold
### BEGIN SOLUTION 
# YOUR CODE HERE
sorted_df = df_sales.sort_values(by=['rating', 'totalunitssold'], ascending=[True, False])
sorted_df
# raise NotImplementedError() 
### END SOLUTION

,listedproducts,totalunitssold,meanunitssoldperproduct,rating,merchantratingscount,meanproductprices,meanretailprices,averagediscount,meandiscount,meanproductratingscount,totalurgencycount,urgencytextrate
merchantid,,,,,,,,,,,,
5e63469b2fdc774466e15dd5,1,10,10.0,2.333,3.0,5.75,5.0,-15.0,-15.0,0.0,NaN,NaN
5e8d923d20c9b7545017f1f9,1,100,100.0,2.941,17.0,11.00,50.0,78.0,78.0,9.0,NaN,NaN
5e6cb9806bab2075b2b64d15,1,100,100.0,3.000,3.0,12.00,11.0,-9.0,-9.0,1.0,NaN,NaN
5e8c98966642021100f8db13,1,100,100.0,3.034,29.0,12.00,75.0,84.0,84.0,28.0,NaN,NaN
5e537a4038654d5bb8db71b4,1,100,100.0,3.039,231.0,5.00,5.0,0.0,0.0,6.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
574d559cb06e205d099d9107,1,10,10.0,4.501,2038.0,18.00,59.0,70.0,70.0,6.0,NaN,NaN
5db248327c0d0800c24fc084,1,10,10.0,4.513,160.0,5.68,5.0,-13.0,-13.0,2.0,NaN,NaN
5b07dc937752c81ecb291b66,1,100,100.0,4.522,343.0,3.73,17.0,79.0,79.0,27.0,NaN,NaN
559f372b577ce1196ef7f66c,1,100,100.0,4.578,1032.0,8.00,47.0,83.0,83.0,110.0,NaN,NaN
5dab9ece69ce753090f6735c,1,100,100.0,5.000,0.0,7.00,6.0,-16.0,-16.0,0.0,NaN,NaN

In [52]:
### Ex-3-Task-5
portion_df = None
### Get the sorted dataframe for which rating is 4.041 and store in portion_df
### BEGIN SOLUTION 
# YOUR CODE HERE
portion_df = sorted_df[sorted_df['rating'] == 4.041]
portion_df
# raise NotImplementedError() 
### END SOLUTION

,listedproducts,totalunitssold,meanunitssoldperproduct,rating,merchantratingscount,meanproductprices,meanretailprices,averagediscount,meandiscount,meanproductratingscount,totalurgencycount,urgencytextrate
merchantid,,,,,,,,,,,,
5810b1db3deb94160f5cd4a3,1,5000,5000.0,4.041,15436.0,6.0,6.0,0.0,0.0,616.0,NaN,NaN
58380161e18c0f0c70dd6907,1,5000,5000.0,4.041,14194.0,8.0,7.0,-14.0,-14.0,1248.0,NaN,NaN
53e98c6446188e1d4d3a38bd,1,1000,1000.0,4.041,4230.0,1.8,2.0,10.0,10.0,76.0,NaN,NaN
580c7d0a8b67fa197454a2d1,3,300,100.0,4.041,4705.0,6.0,6.0,0.0,0.0,27.0,1.0,33.0
5eba4bab58ed6ba265685ba1,2,200,100.0,4.041,123.0,8.0,10.0,20.0,20.0,58.0,1.0,50.0
5b4973b049c8e64e07c31cb4,1,100,100.0,4.041,267.0,9.0,49.0,82.0,82.0,109.0,NaN,NaN

### Data Types and Conversion

In [53]:
### Ex-4-Task-1

# the price of the product is upto 2 digit place. I want to convert it into int
### BEGIN SOLUTION 
# YOUR CODE HERE
df_product['price'] = df_product['price'].astype(int)
df_product['price'].dtype
# raise NotImplementedError() 
### END SOLUTION

dtype('int64')

In [54]:
### Ex-4-Task-2
# The datatype of the craw_month is Object type. I want to convert it to data time format and store it in same columns
### BEGIN SOLUTION 
# YOUR CODE HERE
df_product['crawl_month'] = pd.to_datetime(df_product['crawl_month'], format='%Y-%m')
df_product['crawl_month']
# raise NotImplementedError() 
### END SOLUTION

0      2020-08-01
1      2020-08-01
2      2020-08-01
3      2020-08-01
4      2020-08-01
          ...
1568   2020-08-01
1569   2020-08-01
1570   2020-08-01
1571   2020-08-01
1572   2020-08-01
Name: crawl_month, Length: 1573, dtype: datetime64[ns]

## Data Selection and Filtering

### Selecting Columns and Rows

In [55]:
### Ex-5-Task-1
ser = None 

# Select a 'title' column from product dataframe and store in separate variables as series (ser)
### BEGIN SOLUTION 
# YOUR CODE HERE
ser = df_product['title']
ser
# raise NotImplementedError() 
### END SOLUTION

0       2020 Summer Vintage Flamingo Print  Pajamas Se...
1       SSHOUSE Summer Casual Sleeveless Soirée Party ...
2       2020 Nouvelle Arrivée Femmes Printemps et Été ...
3       Hot Summer Cool T-shirt pour les femmes Mode T...
4       Femmes Shorts d'été à lacets taille élastique ...
                              ...
1568    Nouvelle Mode Femmes Bohême Pissenlit Imprimer...
1569    10 couleurs femmes shorts d'été lacent ceintur...
1570    Nouveautés Hommes Siwmwear Beach-Shorts Hommes...
1571    Mode femmes d'été sans manches robes col en V ...
1572    Pantalon de yoga pour femmes à la mode Slim Fi...
Name: title, Length: 1573, dtype: object

In [56]:
### Ex-5-Task-2
product_price = None 
# Select multiple columns ('title', 'price', and 'retail price' ) from product dataframe and store in variable product_price.
### BEGIN SOLUTION 
# YOUR CODE HERE
product_price = df_product[['title', 'price', 'retail_price']]
product_price
# raise NotImplementedError() 
### END SOLUTION

                                                  title  price  retail_price
0     2020 Summer Vintage Flamingo Print  Pajamas Se...     16            14
1     SSHOUSE Summer Casual Sleeveless Soirée Party ...      8            22
2     2020 Nouvelle Arrivée Femmes Printemps et Été ...      8            43
3     Hot Summer Cool T-shirt pour les femmes Mode T...      8             8
4     Femmes Shorts d'été à lacets taille élastique ...      2             3
...                                                 ...    ...           ...
1568  Nouvelle Mode Femmes Bohême Pissenlit Imprimer...      6             9
1569  10 couleurs femmes shorts d'été lacent ceintur...      2            56
1570  Nouveautés Hommes Siwmwear Beach-Shorts Hommes...      5            19
1571  Mode femmes d'été sans manches robes col en V ...     13            11
1572  Pantalon de yoga pour femmes à la mode Slim Fi...      7             6

[1573 rows x 3 columns]

### Selection by labels and Selection by position

In [57]:
### Ex-5-Task-3
single_data = None
## Select a data of title column and at index 1572 of product dataframe
### BEGIN SOLUTION 
# YOUR CODE HERE
single_data = df_product.loc[1572, 'title']
single_data
# raise NotImplementedError() 
### END SOLUTION

'Pantalon de yoga pour femmes à la mode Slim Fit Fitness Running Leggings'

In [58]:
### Ex-5-Task-4
single_data = None
## Select a data of 6th column and at  5tj row of product dataframe
### BEGIN SOLUTION 
# YOUR CODE HERE
single_data = df_product.iloc[4, 5]
single_data
# raise NotImplementedError() 
### END SOLUTION

np.int64(100)

In [59]:
### Ex-5-Task-5
sliced_data = None 
## Select a portion of data frame with column name currency_buyer, units_sold, merchant_rating_count, merchant_rating and with index 100 to 200
### BEGIN SOLUTION 
# YOUR CODE HERE
sliced_data = df_product.loc[100:200, ['currency_buyer', 'units_sold', 'merchant_rating_count', 'merchant_rating']]
sliced_data
# raise NotImplementedError() 
### END SOLUTION

    currency_buyer  units_sold  merchant_rating_count  merchant_rating
100            EUR         100                    288         3.729167
101            EUR       10000                  54504         3.801684
102            EUR         100                     67         3.298507
103            EUR        5000                  99283         4.285598
104            EUR         100                    239         3.882845
..             ...         ...                    ...              ...
196            EUR        1000                   9341         4.147415
197            EUR       10000                  39381         4.066326
198            EUR        1000                   5048         4.159667
199            EUR        1000                   2377         4.063525
200            EUR        1000                   2996         4.348798

[101 rows x 4 columns]

In [61]:
### Ex-5-Task-6
sliced_data = None 
## Select a portion of data frame with 3rd to 8th columns and with rows 100 to 200 
# it must only include 100 rows and 7 columns 
### BEGIN SOLUTION 
# YOUR CODE HERE
sliced_data = df_product.iloc[100:200, 2:9]
sliced_data.shape
# raise NotImplementedError() 
### END SOLUTION

(100, 7)

### Boolean Indexing and Conditional Filtering

In [63]:
### Ex-5-Task-7
mean = None
Q3 = None 
records = None 
# Find mean and 3rd quantile of the price from product dataframe and get all the records that lies between mean and Q3
### BEGIN SOLUTION 
# YOUR CODE HERE
mean = df_product['price'].mean()
Q3 = df_product['price'].quantile(0.75)
records = df_product[(df_product['price'] > mean) & (df_product['price'] < Q3)]
records
# raise NotImplementedError() 
### END SOLUTION

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
18,Débardeur d'été 5 Couleurs Grandes Tailles été...,5 Color Plus Size Summer New Women Fashion Lad...,9,9,EUR,20000,0,3.82,5479,2456.0,1162.0,853.0,431.0,577.0,0,0,0,0,"Summer,Fashion,tunic,Women Vest,Tank,Tops,tops...",blue,S,50,Livraison standard,3,0,43,50,NaN,NaN,CN,centper3,centper3,"87 % avis positifs (22,089 notes)",22089,4.081624,59cdc2112351344fc0dfa54f,0,NaN,https://www.wish.com/c/5a8f82375e2ae101c8913122,https://contestimg.wish.com/api/webimage/5a8f8...,5a8f82375e2ae101c8913122,summer,2020-08-01
25,2018 Mode d'été Femme Camouflage décontracté C...,2018 Summer Fashion Women Casual Camouflage Ta...,9,32,EUR,1000,0,4.15,567,323.0,116.0,58.0,28.0,42.0,0,0,0,0,"Summer,Vest,Fashion,Tank,Slim T-shirt,camoufla...",armygreen,M,50,Livraison standard,3,0,41,50,NaN,NaN,CN,terbuer,terbuer,"87 % avis positifs (9,395 notes)",9395,4.110059,575cfe470551415caa5505b5,0,NaN,https://www.wish.com/c/5bed2a42bdf0421a30e62c6c,https://contestimg.wish.com/api/webimage/5bed2...,5bed2a42bdf0421a30e62c6c,summer,2020-08-01
26,Nouveau Femme Dentelle Crochet Bikini Maillot ...,New Women Lace Crochet Bikini Cover Up Swimwea...,9,9,EUR,1000,0,4.03,216,105.0,48.0,39.0,12.0,12.0,0,0,0,0,"Summer,midsleevebeachblouse,summerswimsuit,wom...",NaN,M,5,Livraison standard,3,0,60,50,NaN,NaN,US,coaluss,coaluss,"90 % avis positifs (4,298 notes)",4298,4.229409,5a0fe8770a332a615df86c5e,0,NaN,https://www.wish.com/c/5b5edbae1e222732845e655f,https://contestimg.wish.com/api/webimage/5b5ed...,5b5edbae1e222732845e655f,summer,2020-08-01
34,Femmes Mode Gilet Plus La Taille Lâche Casual ...,Women Fashion Vest Plus Size Loose Casual Pure...,9,8,EUR,10000,0,3.80,1231,555.0,240.0,211.0,87.0,138.0,0,0,0,0,"Summer,Vest,Plus Size,Tank,Lace,Tops,Loose,bea...",yellow,S,50,Standart Gönderi,3,0,45,50,NaN,NaN,CN,Sangboo Store,sangboostore,"(10,600 derece)",10600,3.867547,582833faea77701b456c786a,0,NaN,https://www.wish.com/c/5cae1d6c836ecb39e57e9e80,https://contestimg.wish.com/api/webimage/5cae1...,5cae1d6c836ecb39e57e9e80,summer,2020-08-01
40,Sexy Women Casual T-shirt rayé Long Tops Chemi...,Sexy Women Casual Striped T-shirt Long Tops Bl...,9,81,EUR,50000,0,4.26,5359,3111.0,1172.0,650.0,204.0,222.0,1,0,1,0,"blouse,Mini,Fashion,longtop,Shirt,kaftandresse...",black,L,50,Livraison standard,3,0,40,50,NaN,NaN,CN,Fashionshow68,广州乔莎服饰有限公司,"88 % avis positifs (59,198 notes)",59198,4.105054,54bcaabb39b8c00b482a115f,0,NaN,https://www.wish.com/c/556fbe8595528719e004fa27,https://contestimg.wish.com/api/webimage/556fb...,556fbe8595528719e004fa27,summer,2020-08-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1492,Été Nouvelle Mode Col V Imprimé Floral Robe Lâ...,Summer New Fashion V-neck Floral Printed Loose...,9,8,EUR,5000,0,3.47,593,233.0,97.0,95.0,53.0,115.0,0,0,0,0,"Summer,Fashion,Floral,Dresses,Dress,Spaghetti ...",yellow,S,50,Standard Shipping,3,0,32,50,NaN,NaN,CN,justlovemequella,justlovemequella,"83% Positive Feedback (1,821 ratings)",1821,3.981329,58c4f51a77361650efb028df,0,NaN,https://www.wish.com/c/5e8d606bda3e443b5e67bc29,https://contestimg.wish.com/api/webimage/5e8d6...,5e8d606bda3e443b5e67bc29,summer,2020-08-01
1515,Ensemble de t-shirt à manches courtes à manche...,NEW Lovely Women's Colorful Lip Print Rouned N...,9,51,EUR,5000,0,4.11,283,173.0,46.0,18.0,15.0,31.0,0,0,0,0,"Summer,Plus Size,skinny pants,Colorful,pants,W...",black,S,50,Livraison standard,3,0,43,50,1.0,Quantité limitée !,CN,sjhdstoer,sjhdstoer,"(80,093 notes)",80093,4.006692,583138b06339b410ab9663ec,0,NaN,https://www.wish.com/c/5e9693535690ff1a49098d4f,https://contestimg.wish.com/api/webimage/5e969...,5e9693535690ff1a49098d4f,summer,2020-08-01
1538,Fashion Back Lace Up Flower Print Tops Short S...,Fashion Back Lace Up Flower Print Tops Shorts ...,9,8,EUR,1000,1,3.72,489,204.0,100.0,84.0,44.0,57.0,0,0,0,0,"Shorts,Lace,Halter,Pleated,Loose,Backs,Outfits...",white,XXS,5,Livraison standard,3,0,38,50,1.0,Quantité limitée !,CN,Jinqianbao888,jinqianbao888,"86 % avis positifs (40,245 notes)",40245,3.997590,55769de4fa0be7249554bce2,0,NaN,https://www.wish.com/c/5ad96a001c6def05447630a0,https://contestimg.wish.com/api/webimage/5ad96...,5ad96a001c6def05447630a0,summer,2020-08-01
1545,"Summer Fashion Cute "" Dog Mom "" Letter Printed...","Summer Fashion Cute "" Dog Mom "" Letter Print...",9,8,EUR,5000,0,4.28,1120,698.0,205.0,108.0,47.0,62.0,1,0,1,0,"Summer,Fashion,cute,teeshirthomme,summer t-shi...",black,S,50,Livraison standard,3,0,39,50,NaN,NaN,CN,taishon,taishon,"83 % avis positifs (24,564 notes)",24564,3.928880,5763e55cc6053f5e70522ad7,0,NaN,https://www.wish.com/c/5c6ccaed29eb172d628bb404,https://contestimg.wish.com/api/webimage/5c6cc...,5c6ccaed29eb172d628bb404,summer,2020-08-01
1557,fr.delaval.nl : Nouvelle mode d'été pour femme...,HODMEXI™ New Fashion Summer Womens Sexy Party ...,9,76,EUR,20000,0,3.55,7088,2635.0,1394.0,1315.0,715.0,1029.0,0,0,0,0,"Summer,Plus Size,club dresses,Dress,summer dre...",green,S,50,Livraison standard,3,0,36,50,NaN,NaN,CN,HOT DRESS,hotdress,"84 % avis positifs (51,369 notes)",51369,3.968269,539937d634067e06707b1a8e,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/56f0dab6277db57b2a18e14e,https://contestimg.wish.com/api/webimage/56f0d...,56f0dab6277db57b2a18e14e,summer,2020-08-01

In [64]:
### Ex-5-Task-8
summer_product = None 
## Find all the row in product dataframe containing 'summer' keyword in its title. Make sure the string is lower to get all the records. 
### BEGIN SOLUTION 
# YOUR CODE HERE
summer_product = df_product[df_product['title'].str.lower().str.contains('summer')]
summer_product
# raise NotImplementedError() 
### END SOLUTION

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16,14,EUR,100,0,3.76,54,26.0,8.0,10.0,1.0,9.0,0,0,0,0,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,50,Livraison standard,4,0,34,50,1.0,Quantité limitée !,CN,zgrdejia,zgrdejia,(568 notes),568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08-01
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8,22,EUR,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,0,0,0,0,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,50,Livraison standard,2,0,41,50,1.0,Quantité limitée !,CN,SaraHouse,sarahouse,"83 % avis positifs (17,752 notes)",17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08-01
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8,8,EUR,5000,1,4.03,579,295.0,119.0,87.0,42.0,36.0,0,0,0,0,"Summer,Shorts,Cotton,Cotton T Shirt,Sleeve,pri...",black,M,50,Livraison standard,2,0,41,50,NaN,NaN,CN,allenfan,allenfan,"(23,832 notes)",23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08-01
14,2019 Summer Women's Fashion Nouvelle robe sans...,2019 Summer Women's Fashion New Sleeveless Pol...,2,2,EUR,20000,1,3.65,2457,984.0,481.0,459.0,206.0,327.0,0,0,0,0,"Summer,Fashion,Mini,Dress,Loose,Polkas,V-neck,...",yellow,S,1,Livraison standard,1,0,36,50,NaN,NaN,CN,Pentiumhorse,pentiumhorse,"(55,499 notes)",55499,4.138885,5926c5ace8ff5525241b368d,0,NaN,https://www.wish.com/c/5cc2ce18bc97595b6549fa14,https://contestimg.wish.com/api/webimage/5cc2c...,5cc2ce18bc97595b6549fa14,summer,2020-08-01
31,Sweet Beading Cami Débardeurs pour femmes Spag...,Sweet Beading Cami Tank Tops for Women Spaghet...,5,6,EUR,1000,1,4.37,217,137.0,42.0,24.0,9.0,5.0,1,0,1,0,"tank top women,Vest,Beading,Cotton Shirt,camis...",black,XXS,10,Livraison standard,2,0,38,50,NaN,NaN,CN,New Fashion Shopping Park,newfashionshoppingpark,"87 % avis positifs (44,837 notes)",44837,4.065905,54d30f53dc8ce133f79b434d,0,NaN,https://www.wish.com/c/5c9ee457c233fd74ef4c8a84,https://contestimg.wish.com/api/webimage/5c9ee...,5c9ee457c233fd74ef4c8a84,summer,2020-08-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1545,"Summer Fashion Cute "" Dog Mom "" Letter Printed...","Summer Fashion Cute "" Dog Mom "" Letter Print...",9,8,EUR,5000,0,4.28,1120,698.0,205.0,108.0,47.0,62.0,1,0,1,0,"Summer,Fashion,cute,teeshirthomme,summer t-shi...",black,S,50,Livraison standard,3,0,39,50,NaN,NaN,CN,taishon,taishon,"83 % avis positifs (24,564 notes)",24564,3.928880,5763e55cc6053f5e70522ad7,0,NaN,https://www.wish.com/c/5c6ccaed29eb172d628bb404,https://contestimg.wish.com/api/webimage/5c6cc...,5c6ccaed29eb172d628bb404,summer,2020-08-01
1551,New Fashion Women's Summer Drawstring Pants L...,New Fashion Women's Summer Drawstring Pants L...,7,6,EUR,100,1,3.67,18,7.0,3.0,5.0,1.0,2.0,0,0,0,0,"drawstringpant,Summer,Shorts,Bottom,pants,Loos...",khaki,M,44,Livraison standard,2,0,23,50,NaN,NaN,CN,Suyi Technology,greatexpectationstechnology,"86 % avis positifs (12,309 notes)",12309,4.045170,5acaf29d5ebcfd72403106a8,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/5cc7b4c98b94871ee33b33b6,https://contestimg.wish.com/api/webimage/5cc7b...,5cc7b4c98b94871ee33b33b6,summer,2020-08-01
1556,Summer Beach Safety Shorts Leggings Lady Leggi...,Summer Beach Safety Shorts Lady Leggings Pants...,7,6,EUR,1000,1,3.98,129,64.0,21.0,28.0,9.0,7.0,1,1,0,0,"undersafetypant,Summer,Underwear,Panties,high ...",white,XS,50,Livraison standard,2,0,27,50,NaN,NaN,CN,Shades Darker,shadesdarker,(794 notes),794,4.277078,58b7d6dd3c18975a18817d64,0,NaN,https://www.wish.com/c/5cb1abbb53de5b5d80d22e2e,https://contestimg.wish.com/api/webimage/5cb1a...,5cb1abbb53de5b5d80d22e2e,summer,2020-08-01
1562,Summer Women s Fashion Lace Up Tie Pants Plus...,Summer Women s Fashion Lace Up Tie Pants Plus...,4,6,EUR,100,0,3.77,47,22.0,7.0,8.0,5.0,5.0,0,0,0,0,"Summer,Shorts,Lace,pants,Waist,Short pants,Yel...",red,S,1,Standard Shipping,1,0,41,50,NaN,NaN,CN,SaraHouse,sarahouse,"83% Positive Feedback (17,752 ratings)",17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/5d58daef3159a812b05933d2,https://contestimg.wish.com/api/webimage/5d58d...,5d58daef3159a812b05933d2,summer,2020-08-01
1570,Nouveautés Hommes Siwmwear Beach-Shorts Hommes...,New Men Siwmwear Beach-Shorts Men Summer Quick...,5,19,EUR,100,0,3.71,59,24.0,15.0,8.0,3.0,9.0,0,0,0,0,"runningshort,Beach Shorts,beachpant,menbeachsh...",white,SIZE S,15,Livraison standard,2,0,11,50,NaN,NaN,CN,shixueying,shixueying,86 % avis positifs (210 notes),210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08-01

## Handling Missing Data

In [71]:
### Ex-6-Task-1
count_na = None
# Count the number of null data in each columns
### BEGIN SOLUTION 
# YOUR CODE HERE
count_na = df_product.apply(pd.isna).sum()
count_na
# raise NotImplementedError() 
### END SOLUTION

title                              0
title_orig                         0
price                              0
retail_price                       0
currency_buyer                     0
units_sold                         0
uses_ad_boosts                     0
rating                             0
rating_count                       0
rating_five_count                 45
rating_four_count                 45
rating_three_count                45
rating_two_count                  45
rating_one_count                  45
badges_count                       0
badge_local_product                0
badge_product_quality              0
badge_fast_shipping                0
tags                               0
product_color                     41
product_variation_size_id         14
product_variation_inventory        0
shipping_option_name               0
shipping_option_price              0
shipping_is_express                0
countries_shipped_to               0
inventory_total                    0
has_urgency_banner              1100
urgency_text                    1100
origin_country                    17
merchant_title                     0
merchant_name                      4
merchant_info_subtitle             1
merchant_rating_count              0
merchant_rating                    0
merchant_id                        0
merchant_has_profile_picture       0
merchant_profile_picture        1347
product_url                        0
product_picture                    0
product_id                         0
theme                              0
crawl_month                        0
dtype: int64

In [77]:
### Ex-6-Task-2

# Impute the  product color with maximum occur value as it is the categorical columns 
# Impute the rating five count by mean and rating four count by median of respective columns
### BEGIN SOLUTION 
# YOUR CODE HERE
df_product['product_color'].fillna(df_product['product_color'].mode()[0], inplace=True)
df_product['rating_five_count'].fillna(df_product['rating_five_count'].mean(), inplace=True)
df_product['rating_four_count'].fillna(df_product['rating_four_count'].median(), inplace=True)
df_product[['product_color','rating_five_count', 'rating_four_count']].isna().sum()
# raise NotImplementedError() 
### END SOLUTION

/tmp/ipykernel_52685/2192423640.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_product['rating_five_count'].fillna(df_product['rating_five_count'].mean(), inplace=True)
/tmp/ipykernel_52685/2192423640.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_product['rating_four_count'].fillna(df_product['rating_four_count'].median(), inplace=True)

product_color        0
rating_five_count    0
rating_four_count    0
dtype: int64

## Data Cleaning

### Removing Duplicates

In [78]:
### Ex-7-Task-1
duplicate_count = None
df_drop_duplicate = None # store the data frame after removing duplicates 
# Count no. of duplicates value in product dataframe and drop all the duplicate values 
### BEGIN SOLUTION 
# YOUR CODE HERE
duplicate_count = df_product.duplicated().sum()
df_drop_duplicate = df_product.drop_duplicates()
# raise NotImplementedError() 
### END SOLUTION

## Data Transformation

### Applying Functions: Apply, map

In [80]:
### Ex-7-Task-2

df_sales['total_profit'] = None
# Calculate the total profit using apply function in pandas and save in total_profit column
# Formulae: total_profit = (mean product price - mean retail price) * total units sold
### BEGIN SOLUTION 
# YOUR CODE HERE
df_sales['total_profit'] = df_sales.apply(lambda row: (row['meanproductprices'] - row['meanretailprices']) * row['totalunitssold'], axis=1)
df_sales['total_profit']
# raise NotImplementedError() 
### END SOLUTION

merchantid
5357bcf2bb72c5504882e889   -1320000.00
5708773c3c02161b3f8c7900   -2831724.00
5417aada4ad3ab27e954b76c          0.00
570f3a713a698c14278bb51e   -1333000.00
53082ea15aefb07dfe1f2a4f   -2800000.00
                               ...
567bad8582c35f28103e5813          2.00
5b24edf0d1c360301099e9c6          0.00
5d417e7070327a2743021677         -6.28
5add589edb5f1f32114d07df          0.00
5d4b8931933fb13f8a1fe232        -19.00
Name: total_profit, Length: 958, dtype: float64

### Binning and Categorizing Data

In [82]:
### Ex-7-Task-3
df_product['sales_category'] = None
# Divide the row into three category based on their units sold and save it into the sales_category column of produdct dataframe
# category are : low_sales, medium sales, and high sales 
### BEGIN SOLUTION 
# YOUR CODE HERE
def categorize_sales(units_sold):
    if units_sold < 1000:
        return 'low_sales'
    elif 1000 <= units_sold < 5000:
        return 'medium_sales'
    else:
        return 'high_sales'
df_product['sales_category'] = df_product['units_sold'].apply(categorize_sales)
df_product['sales_category'].value_counts()
# raise NotImplementedError() 
### END SOLUTION

sales_category
low_sales       648
high_sales      520
medium_sales    405
Name: count, dtype: int64

## Data Aggregation and Grouping

### Groupby aggregation function

In [86]:
### Ex-8-Task-1

group_df = None 
# Create a group of low, medium and high sales and then calulcate, mean of price, median of retail price, min of units_sold and max of rating_five_count of each category
### BEGIN SOLUTION 
# YOUR CODE HERE
group_df = df_product.groupby('sales_category', as_index=False).agg({
                'price': 'mean',
                'retail_price': 'median',
                'units_sold': 'min',
                'rating_five_count': 'max'
            })
group_df
# raise NotImplementedError() 
### END SOLUTION

  sales_category     price  retail_price  units_sold  rating_five_count
0     high_sales  8.296154          10.0        5000       11548.000000
1      low_sales  7.953704          10.0           1         442.263743
2   medium_sales  8.456790          11.0        1000         520.000000

In [ ]:
### Ex-8-Task-2
group_df = None
## Calculate the Coefficient of Variation of each sales category
### BEGIN SOLUTION 
# YOUR CODE HERE
group_df = df_product.groupby('sales_category', as_index=False).agg({
                'price': lambda x: np.std(x) * 100 / np.mean(x),
                'retail_price': lambda x: np.std(x) * 100 / np.mean(x),
                'units_sold': lambda x: np.std(x) * 100/ np.mean(x),
                'rating_five_count': lambda x: np.std(x) * 100/ np.mean(x)
            })
group_df
# raise NotImplementedError() 
### END SOLUTION

  sales_category     price  retail_price  units_sold  rating_five_count
0     high_sales  0.409392      1.413899    1.068294           1.192967
1      low_sales  0.582485      1.235119    0.348953           2.554731
2   medium_sales  0.458331      1.271827    0.000000           0.792736

In [89]:
### Ex-8-Task-3
df_product['price_zscore'] = None
## Calculate the Z_score of price for each sales category
### BEGIN SOLUTION 
# YOUR CODE HERE
df_product['price_zscore'] = df_product.groupby('sales_category')['price'].transform(lambda x: (x - x.mean()) / x.std())
df_product[['sales_category', 'price', 'price_zscore']]
# raise NotImplementedError() 
### END SOLUTION

     sales_category  price  price_zscore
0         low_sales     16      1.735427
1        high_sales      8     -0.087113
2         low_sales      8      0.009985
3        high_sales      8     -0.087113
4         low_sales      2     -1.284096
...             ...    ...           ...
1568     high_sales      6     -0.675410
1569      low_sales      2     -1.284096
1570      low_sales      5     -0.637055
1571      low_sales     13      1.088386
1572      low_sales      7     -0.205695

[1573 rows x 3 columns]

## Merging

In [92]:
### Ex-9-Task-1
merged_df = None
# Merge the sales and product dataframe and delete all the non common entries. Merge two dataframe based on merchant id.
### BEGIN SOLUTION 
# YOUR CODE HERE
merged_df = pd.merge(df_sales, df_product,left_on= 'merchantid', right_on='merchant_id', how='inner')
merged_df
# raise NotImplementedError() 
### END SOLUTION

,listedproducts,totalunitssold,meanunitssoldperproduct,rating_x,merchantratingscount,meanproductprices,meanretailprices,averagediscount,meandiscount,meanproductratingscount,totalurgencycount,urgencytextrate,total_profit,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating_y,rating_count,rating_five_count,rating_four_count,rating_three_count,...,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month,sales_category,price_zscore
0,2,120000,60000.0,4.219,320031.0,9.00,20.0,54.0,54.0,8836.0,1.0,50.0,-1320000.00,Femmes dentelle manches courtes hauts hauts ch...,Women Lace Short Sleeve Long Tops Blouse Shirt...,7,22,EUR,100000,1,3.82,11913,5355.000000,2430.0,1974.0,...,S,50,Livraison standard,2,0,46,50,NaN,NaN,CN,ApparelHeaven,primesalecolimited,"90 % avis positifs (320,031 notes)",320031,4.218866,5357bcf2bb72c5504882e889,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/567cb0925ff12c4829f07dfb,https://contestimg.wish.com/api/webimage/567cb...,567cb0925ff12c4829f07dfb,summer,2020-08-01,high_sales,-0.381261
1,2,120000,60000.0,4.219,320031.0,9.00,20.0,54.0,54.0,8836.0,1.0,50.0,-1320000.00,Femmes Chemisier d'été Chemise Sexy Floral Che...,Womens Summer Blouse Sexy Floral Shirt Loose K...,11,18,EUR,20000,1,4.14,5759,3125.000000,1205.0,838.0,...,S,50,Livraison standard,3,0,46,50,1.0,Quantité limitée !,CN,ApparelHeaven,primesalecolimited,"90 % avis positifs (320,031 notes)",320031,4.218866,5357bcf2bb72c5504882e889,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/572981a997dc5f5d3c5f0651,https://contestimg.wish.com/api/webimage/57298...,572981a997dc5f5d3c5f0651,summer,2020-08-01,high_sales,0.795332
2,5,107100,21420.0,3.934,139223.0,7.76,34.2,61.0,61.0,4010.0,3.0,60.0,-2831724.00,2018 New Fashion Women's Tops Sexy Strappy Sle...,2018 New Fashion Women's Tops Sexy Strappy Sle...,5,25,EUR,100000,1,3.83,17980,8290.000000,3483.0,2951.0,...,S,50,Livraison standard,1,0,41,50,1.0,Quantité limitée !,CN,leiston,leiston,"84 % avis positifs (139,223 notes)",139223,3.933581,5708773c3c02161b3f8c7900,0,NaN,https://www.wish.com/c/5b07a7c6e997b33c6f9947da,https://contestimg.wish.com/api/webimage/5b07a...,5b07a7c6e997b33c6f9947da,summer,2020-08-01,high_sales,-0.969558
3,5,107100,21420.0,3.934,139223.0,7.76,34.2,61.0,61.0,4010.0,3.0,60.0,-2831724.00,Femmes Mode Couleur Unie Sexy Col En V Tops Cr...,Women Fashion Solid Color Sexy V-neck Crop Top...,8,7,EUR,100,1,3.52,23,9.000000,3.0,4.0,...,S,17,Livraison standard,3,0,41,50,1.0,Quantité limitée !,CN,leiston,leiston,"84 % avis positifs (139,223 notes)",139223,3.933581,5708773c3c02161b3f8c7900,0,NaN,https://www.wish.com/c/5e9692898a10221b310986c9,https://contestimg.wish.com/api/webimage/5e969...,5e9692898a10221b310986c9,summer,2020-08-01,low_sales,0.009985
4,5,107100,21420.0,3.934,139223.0,7.76,34.2,61.0,61.0,4010.0,3.0,60.0,-2831724.00,Nouveau Summer Women's Fashion Bikini Set coul...,New Summer Women 's Fashion Bikini Set Solid C...,14,37,EUR,1000,0,3.85,422,189.000000,102.0,55.0,...,M,50,Livraison standard,4,0,41,50,1.0,Quantité limitée !,CN,leiston,leiston,"84 % avis positifs (139,223 notes)",139223,3.933581,5708773c3c02161b3f8c7900,0,NaN,https://www.wish.com/c/5cece16810467a5f254abaa9,https://contestimg.wish.com/api/webimage/5cece...,5cece16810467a5f254abaa9,summer,2020-08-01,medium_sales,1.428367
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,1,2,2.0,3.999,21307.0,11.00,10.0,-10.0,-10.0,1.0,NaN,NaN,2.00,Femmes T-shirt à rayures à carreaux Chemisier ...,Women Plaid Stripes T Shirt V-neck Short Sleev...,11,10,EUR,2,0,2.00,1,0.000000,0.0,0.0,...,S,50,Livraison standard,3,0,19,50,NaN,NaN,CN,"Guangzhou Fashion Girl co.,ltd",guangzhoufashiongirlcoltd,"86 % avis positifs (21,307 notes)",21307,3.999061,567bad8582c35f28103e5813,0,NaN,https://www.wish.com/c/5ed8983fb83b7828822ad26a,https://contestimg.wish.com/api/webimage/5ed89...,5ed8983fb83b7828822ad26a,summer,2020-08-01,low_sales,0.657026
1569,1,2,2.0,4.303,693.0,16.00,16.0,0.0,0.0,0.0,NaN,NaN,0.00,Ventilateur personnel USB rechargeable mains l...,Personal Fan USB Rechargeable Hands Free Neckb...,16,16,EUR,2,0,5.00,0,442.263743,31.5,NaN,...,White,10,Livraison standard,5,0,32,50,NaN,NaN,CN,xiaoguiling,xiaoguiling,(693 notes),693,4.303030,5b24edf0d1c360301099e9c6,0,NaN,https://www.wish.com/c/5f11698e9a44cd5ecd1909db,https://contestimg.wish.com/api/webimage/5f116...,5f11698e9a44cd5ecd1909db,summer,2020-08-01,low_sales,1.735427
1570,1,1,1.0,3.598,378.0,2.72,9.0,70.0,70.0,0.0,NaN,NaN,-6.28,Women's Casual Sleeveless Stripe T Shirts Dres...,Women's Casual Sleeveless Stripe T Shirts Dres...,2,9,EUR,1,0,5.00,0,442.263743,31.5,NaN,...,XS,1,Livraison standard,1,0,33,50,NaN,NaN,CN,Kyiswen,kyiswen,75 % avis positifs (378 notes),378,3.597884,5d417e7070327a2743021677,0,NaN,https://www.wish.com/c/5ed3ae8e7bf8821d5cf4bc64,https://contestimg.wish.com/api/webimage/5ed3a...,5ed3ae8e7bf8821d5cf4bc64,summer,2020-08-01,low_sales,-1.284096
1571,1,1,1.0,3.956,1134.0,14.00,14.0,0.0,0.0,0.0,NaN,NaN,0.00,Nouvelles femmes d'été mode couleur unie short...,New Women Summer Fashion Solid Color Shorts Ca...,14,14,EUR,1,0,5.00,0,442.263743,31.5,NaN,...,XXS,5,Livraison standard,4,0,27,50,NaN,NaN,CN,gaomeigui,gaomeigui,"84 % avis positifs (1,134 notes)",1134,3.955908,5add589edb5f1f32114d07df,0,NaN,https://www.wish.com/c/5eccb455d4eb5d46b00be0ed,https://contestimg.wish.com/api/webimage/5eccb...,5eccb455d4eb5d46b00be0ed,summer,2020-08-01,low_sales,1.304066
1572,1,1,1.0,4.007,1380.0,11.00,30.0,64.0,64.0,0.0,NaN,NaN,-19.00,Combinaisons décontractées sans manches en cot...,Women Summer Fashion Cotton Overalls Sleeveles...,11,30,EUR,1,0,5.00,0,442.263743,31.5,NaN,...,XS,10,Livraison standard,2,0,33,50,NaN,NaN,CN,caogao,caogao,"(1,380 notes)",1380,4.007246,5d4b8931933fb13f8a1fe232,0,NaN,https://www.wish.com/c/5ebfdd5bebac37702b0b207b,https://contestimg.wish.com/api/webimage/5ebfd...,5ebfdd5bebac37702b0b207b,summer,2020-08-01,low_sales,0.657026

# Data Wrangling End to End

## Data Cleaning

#### Features and Columns 
The data was scraped in the french localisation (hence some non-ascii latin characters such as « é » and « à ») in the title column.

The title_orig on the other hand contains the original title (the base title) that is displayed by default. When a translation is provided by the seller, it appears in the title column. When the title and title_orig columns are the same, it generally means that the seller did not specify a translation that would be displayed to users with french settings.

A picture is worth a thousand words. In the following screenshot you see some features and how to interpret them.

![](wish_viz.jpg)

In [99]:
### Ex-10-Task-1
df = None 
# Read the product data frame with rating and performance 
### BEGIN SOLUTION 
# YOUR CODE HERE
df = pd.read_csv('summer-products-with-rating-and-performance_2020-08.csv')
# raise NotImplementedError() 
### END SOLUTION

There are total 43 columns. Let's try to reduce the number. 

#### Some considerations:
- Excluded product color and size because it's just showing the ones that were found in getting the data : there are more colors and sizes for each product so having just one for each category doesn't say much.
- Excluded currency used, as every price is in EUR
- Excluded shipping option, the "shipping_is_express" column is enough.
- Excluded product's and merchant's id's and pictures, that won't be needed.
- Use only original title

After removal of column, it must only have these columns. 

'title_orig', 'price', 'retail_price',
'units_sold', 'uses_ad_boosts', 'rating', 'rating_count',
'rating_five_count', 'rating_four_count', 'rating_three_count',
'rating_two_count', 'rating_one_count', 'badges_count',
'badge_local_product', 'badge_product_quality', 'badge_fast_shipping',
'tags', 'shipping_option_price', 'shipping_is_express', 'countries_shipped_to',
'inventory_total', 'has_urgency_banner',
'merchant_rating_count', 'merchant_rating',
'merchant_has_profile_picture'

In [100]:
### Ex-10-Task-2
df = df[['title_orig', 'price', 'retail_price',
        'units_sold', 'uses_ad_boosts', 'rating', 'rating_count',
       'rating_five_count', 'rating_four_count', 'rating_three_count',
       'rating_two_count', 'rating_one_count', 'badges_count',
       'badge_local_product', 'badge_product_quality', 'badge_fast_shipping',
       'tags', 'shipping_option_price','shipping_is_express', 'countries_shipped_to',
        'has_urgency_banner','merchant_rating_count', 'merchant_rating','merchant_has_profile_picture',
        ]]

# print(df.info())
# print(df.isna().sum())
# print(df['has_urgency_banner'].value_counts())
# Check the data frame information, total no. of null entries in each columns and has_urgency_banner columns counts
# After loading the data we se we have 1573 entries and some null values, let's see what some of them are about:
# - Exactly 45 for rating counts from 1 to 5 star, could it be that there are products with no ratings at all?
# - 1100 null values in the has urgency banner : the values there are 1's so the null values should be turned into 0's
# Now, Rename the columns 'has_urgency_banner' to 'is_running_out' and 'title_orig' to 'title' to make it more clear.
# **Fix the runing out column. fill all the null values with 0's.
### BEGIN SOLUTION 
# YOUR CODE HERE
df['has_urgency_banner'].fillna(0, inplace=True)
df.rename(columns={'has_urgency_banner': 'is_running_out', 'title_orig': 'title'}, inplace=True)
# raise NotImplementedError() 
### END SOLUTION

/tmp/ipykernel_52685/1609802097.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['has_urgency_banner'].fillna(0, inplace=True)

#### Check if all the 45 null values for all rating columns belong to same product.
- Get the dataframe for which rating_five_count have null values
- Then, Count the no. of null values for four, three, two and one rating column.

Conclusion: As expected we see the null values in the rating are actually of the same 45 products

In [103]:
### Ex-10-Task-3
df[df['rating_five_count'].isna()][['rating_four_count', 'rating_three_count',
       'rating_two_count', 'rating_one_count']].isna().sum()
df[df['rating_five_count'].isna()].head()
# They seem to be having a rating of 5 even with no ratings: we are going to change the rating and all the rating counts to 0
### BEGIN SOLUTION 
# YOUR CODE HERE
df.loc[df['rating_five_count'].isna(), 'rating'] = 0    
df.loc[df['rating_five_count'].isna(), ['rating_five_count', 'rating_four_count', 
                                         'rating_three_count', 'rating_two_count', 
                                         'rating_one_count']] = 0
# raise NotImplementedError() 
### END SOLUTION

## Data Exploration

```df['units_sold'].unique()```

It seems like they are all numbers approximated to their lower bound. So let's pretend they are divided in ranges like this:

- 10-100
- 100-1000
- 1000-5000
- 5000-10000
- 10000-20000
- 20000-50000
- 50000-100000
- 100000+

Let's define 3 performance characteristics:

- Average : 0-1000
- Successful: 1000-20000
- Very Successful 20000+

Find the percentage of product belongs to each category.
Steps:
1. First find the performance category and store in performance columns
2. Then, Calculate the percentage of product in each performance category

In [104]:
### Ex-10-Task-4
percentage_of_product_in_each_performance_category = None
### BEGIN SOLUTION 
# YOUR CODE HERE
df['performance_category'] = df['units_sold'].map(lambda x: 'Averge' if x<1000 else ('Successful' if x<20000 else 'Very Successful')) 
percentage_of_product_in_each_performance_category = df['performance_category'].value_counts(normalize=True) * 100
percentage_of_product_in_each_performance_category
# raise NotImplementedError() 
### END SOLUTION

performance_category
Successful         50.794660
Averge             41.195168
Very Successful     8.010172
Name: proportion, dtype: float64

## Product Rating and Performance Comparision

Looking at the rating columns I notice two things:

- Some products have a rating count that's too low to be considered, let's only look at products with more than 150 ratings to try to have a fair result
- The rating of the products is a decimal number: let's create another column that categorizes each product into it's rating range.
    - columns are 
        1. < 1 if rating < 1
        2. 1-2 if rating >= 1 and rating < 2
        3. 2-3 if rating >= 2 and rating < 3
        4. 3-4 if rating >= 3 and rating < 4
        5. 4-5 if rating >= 4 and rating < 5
- Create pivot table with performance in index, raiting_range in column and no. of product as values

In [107]:
### Ex-10-Task-5
df_ratings = pd.DataFrame()  ## get records with rating_count > 100
df_ratings['rating_range'] = None
pivot_table = None
### BEGIN SOLUTION 
# YOUR CODE HERE
df_ratings = df[df['rating_count'] > 150].copy()
df_ratings['rating_range'] = df_ratings['rating'].map(lambda x: '1-2' if x < 2 else ('2-3' if x < 3 else ('3-4' if x < 4 else '4-5')))
pivot_table = df_ratings.pivot_table(index='rating_range', columns='performance_category', values='title', aggfunc='count', fill_value=0)
pivot_table
# raise NotImplementedError() 
### END SOLUTION

performance_category  Averge  Successful  Very Successful
rating_range
2-3                        0           4                2
3-4                        3         402               78
4-5                        0         250               46

This table shows that if the product have average rating of 3-4. THen, it is most likely to be successful product.